version: 0.2

phases:
  install:
    commands:
      - CODEBUILD_PROJECT_NAME=$(echo $CODEBUILD_BUILD_ID | cut -d ':' -f 1)
      - curl -O https://releases.hashicorp.com/packer/1.9.2/packer_1.9.2_linux_amd64.zip
      - unzip packer_1.9.2_linux_amd64.zip
      - mv packer /usr/bin/

  build:
    commands:
      - ./build-wrapper.sh
